MODEL:
  TYPE: TransNet
  NAME: transnet_tiny_96
  DROP_PATH_RATE: 0.3
  TransNet:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2 ,2]
    NUM_HEADS: [ 3, 6, 6]
  DISCRIMINIATOR:
    IN_CHANS: 2
    EMBED_DIM: 96
    NLAYERS: 2
    NORM_LAYER: 'instance'
