MODEL:
  TYPE: TransNet
  NAME: transnet_tiny_64
  DROP_PATH_RATE: 0.1
  DROP_RATE: 0.1
  TransNet:
    EMBED_DIM: 64
    DEPTHS: [4,4, 4]
    NUM_DOWN: 3
    NUM_HEADS: [ 1, 3,6]
  DISCRIMINIATOR:
    IN_CHANS: 2
    EMBED_DIM: 96
    NLAYERS: 2
    NORM_LAYER: 'instance'
  NUMS_PATTERN_MODE: 128
  NUMS_NOSIE_MODE: 128
