MODEL:
  TYPE: ConvNet
  NAME: convnet_original_64_2_4
  ConvNet:
    BASE_CH: 64
    NUM_DOWN: 2
    NUM_RESIDUAL: 4
    RES_NORM: 'instance'
    DOWN_NORM: 'instance'
    UP_NORM: 'layer'
  DISCRIMINIATOR:
    IN_CHANS: 2
    EMBED_DIM: 96
    NLAYERS: 2
    NORM_LAYER: 'instance'
